name: Pamplejuce

on:
  workflow_dispatch: # lets you run a build from the UI
  push:

# When pushing new commits, cancel any running builds on that branch
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Release
  BUILD_DIR: Builds
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DISPLAY: :0 # linux pluginval needs this
  CMAKE_BUILD_PARALLEL_LEVEL: 3 # Use up to 3 cpus to build juceaide, etc
  HOMEBREW_NO_INSTALL_CLEANUP: 1

# jobs are run in paralell on different machines
# all steps run in series
jobs:
  build_and_test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # show all errors for each platform (vs. cancel jobs on error)
      matrix:
        include:
          - name: macOS
            os: macos-12
            pluginval-binary: pluginval.app/Contents/MacOS/pluginval
            ccache: ccache
          - name: Linux
            os: ubuntu-22.04
            pluginval-binary: ./pluginval
            ccache: ccache
        #  - name: Windows
         #   os: windows-latest
          #  pluginval-binary: ./pluginval.exe
           # ccache: sccache

    steps:
    # This is just easier than debugging different compilers on different platforms
    - name: Set up Clang
      if: ${{ matrix.name != 'macOS' }}
      uses: egor-tensin/setup-clang@v1

    # This also starts up our "fake" display Xvfb, needed for pluginval
    - name: Install JUCE's Linux Deps
      if: runner.os == 'Linux'
      # Thanks to McMartin & co https://forum.juce.com/t/list-of-juce-dependencies-under-linux/15121/44
      run: |
        sudo apt-get update && sudo apt install libasound2-dev libx11-dev libxinerama-dev libxext-dev libfreetype6-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev xvfb ninja-build
        sudo /usr/bin/Xvfb $DISPLAY &

    - name: Cache IPP (Windows)
      if: runner.os == 'Windows'
      id: cache-ipp
      uses: actions/cache@v3
      with:
        key: ipp-v1
        path: C:\Program Files (x86)\Intel\oneAPI\ipp

    - name: Install IPP (Windows)
      if: (runner.os == 'Windows') && (steps.cache-ipp.outputs.cache-hit != 'true')
      shell: bash
      run: |
        curl --output oneapi.exe https://registrationcenter-download.intel.com/akdlm/irc_nas/19078/w_BaseKit_p_2023.0.0.25940_offline.exe
        ./oneapi.exe -s -x -f oneapi
        ./oneapi/bootstrapper.exe -s -c --action install --components=intel.oneapi.win.ipp.devel --eula=accept -p=NEED_VS2022_INTEGRATION=1 --log-dir=.

    - name: Save IPP cache even on job fail
      if: runner.os == 'Windows' && (steps.cache-ipp.outputs.cache-hit != 'true')
      uses: actions/cache/save@v3
      with:
        path: C:\Program Files (x86)\Intel\oneAPI\ipp
        key: ipp-v1

    # This lets us use sscache on Windows
    # We need to install ccache here for Windows to grab the right version
    - name: Install Ninja (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: choco install ninja ccache

    - name: Install macOS Deps
      if: ${{ matrix.name == 'macOS' }}
      run: brew install ninja osxutils

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true # Get JUCE populated

    - name: ccache
      uses: hendrikmuhs/ccache-action@main
      with:
        key: v3-${{ matrix.os }}-${{ matrix.type }}
        variant: ${{ matrix.ccache }}

    - name: Import Certificates (macOS)
      uses: apple-actions/import-codesign-certs@v2 # only exists as a tag right now
      if: ${{ matrix.name == 'macOS' }}
      with:
        p12-file-base64: ${{ secrets.DEV_ID_INSTALL_CERT }}
        p12-password: ${{ secrets.DEV_ID_INSTALL_PASSWORD }}

    - name: Configure
      shell: bash
      run: cmake -B ${{ env.BUILD_DIR }} -G Ninja -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE}} -DCMAKE_C_COMPILER_LAUNCHER=${{ matrix.ccache }} -DCMAKE_CXX_COMPILER_LAUNCHER=${{ matrix.ccache }} -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" .

    - name: Build
      shell: bash
      run: cmake --build ${{ env.BUILD_DIR }} --config ${{ env.BUILD_TYPE }} --parallel 4

    - name: Test
      working-directory: ${{ env.BUILD_DIR }}
      run: ctest --output-on-failure -j4 -VV

    - name: Read in .env from CMake # see GitHubENV.cmake
      shell: bash
      run: |
        cat .env # show us the config
        cat .env >> $GITHUB_ENV # pull in our PRODUCT_NAME, etc

    - name: Set additional env vars for next steps
      shell: bash
      run: |
        echo "ARTIFACTS_PATH=${{ env.BUILD_DIR }}/${{ env.PROJECT_NAME }}_artefacts/${{ env.BUILD_TYPE }}" >> $GITHUB_ENV
        echo "VST3_PATH=${{ env.PROJECT_NAME }}_artefacts/${{ env.BUILD_TYPE }}/VST3/${{ env.PRODUCT_NAME }}.vst3" >> $GITHUB_ENV
        echo "AU_PATH=${{ env.PROJECT_NAME }}_artefacts/${{ env.BUILD_TYPE }}/AU/${{ env.PRODUCT_NAME }}.component" >> $GITHUB_ENV
        echo "ARTIFACT_NAME=${{ env.PRODUCT_NAME }}-${{ env.VERSION }}-${{ matrix.name }}" >> $GITHUB_ENV
     #   echo "AAX_PATH=${{ env.PROJECT_NAME }}_artefacts/${{ env.BUILD_TYPE }}/AAX/${{ env.PRODUCT_NAME }}.aaxplugin" >> $GITHUB_ENV          
        

    - name: Pluginval
      working-directory: ${{ env.BUILD_DIR }}
      shell: bash
      run: |
        curl -LO "https://github.com/Tracktion/pluginval/releases/download/v1.0.3/pluginval_${{ matrix.name }}.zip"
        7z x pluginval_${{ matrix.name }}.zip
        ${{ matrix.pluginval-binary }} --strictness-level 10 --verbose --validate "${{ env.VST3_PATH }}"

    - name: Codesign (macOS)
      working-directory: ${{ env.BUILD_DIR }}
      if: ${{ matrix.name == 'macOS' }}
      run: |
        # Each plugin must be code signed
        codesign --force -s "${{ secrets.DEVELOPER_ID_INSTALLER }}" -v "${{ env.VST3_PATH }}" --deep --strict --options=runtime --timestamp
        codesign --force -s "${{ secrets.DEVELOPER_ID_INSTALLER }}" -v "${{ env.AU_PATH }}" --deep --strict --options=runtime --timestamp

  #  - name: Add Custom Icons (macOS)
#      if: ${{ matrix.name == 'macOS' }}
#      working-directory: ${{ env.BUILD_DIR }}
#      run: |
#        # add the icns as its own icon resource (meta!)
#        sips -i ../packaging/pamplejuce.icns
#        
#        # Grab the resource, put in tempfile
#        DeRez -only icns ../packaging/pamplejuce.icns > /tmp/icons
#        
#        # Stuff the resource into the strange Icon? file's resource fork
#        Rez -a /tmp/icons -o "${{ env.VST3_PATH }}/Icon"$'\r'
#        Rez -a /tmp/icons -o "${{ env.AU_PATH }}/Icon"$'\r'
#        
#        # Set custom icon attribute
#        SetFile -a C "${{ env.VST3_PATH }}"
#        SetFile -a C "${{ env.AU_PATH }}"

    - name: Create Pkg installers and sign
      if: ${{ matrix.name == 'macOS' }}
      shell: bash
      run: |
        PRODUCT_NAME="${{ env.PRODUCT_NAME }}"
        INSTALLER_USER_ID="${{ secrets.DEVELOPER_ID_INSTALLER }}"
        PATH_TO_VST3="Builds/${{ env.VST3_PATH }}"
        PATH_TO_AU="Builds/${{ env.AU_PATH }}"
        pkgbuild --identifier "com.ShizanaPlugins.${PRODUCT_NAME}.vst3.pkg" --root ${PATH_TO_VST3} --install-location /Library/Audio/Plug-Ins/VST3 "com.ShizanaPlugins.${PRODUCT_NAME}.vst3.pkg"
        pkgbuild --identifier "com.ShizanaPlugins.${PRODUCT_NAME}.component.pkg" --root ${PATH_TO_AU} --install-location /Library/Audio/Plug-Ins/Components "com.ShizanaPlugins.${PRODUCT_NAME}.component.pkg"
        mkdir Signed
        productbuild --distribution "packaging/Pkg/Signed/distribution.xml" --package-path "Signed/" "${PRODUCT_NAME}_NotSign.pkg"
      # productsign --sign "${{ secrets.DEVELOPER_ID_INSTALLER }}" "com.ShizanaPlugins.${PRODUCT_NAME}.vst3.pkg" "Signed/com.ShizanaPlugins.${PRODUCT_NAME}.vst3.pkg"
      #  productsign --sign "${{ secrets.DEVELOPER_ID_INSTALLER }}" "com.ShizanaPlugins.${{ env.PRODUCT_NAME }}.component.pkg" "Signed/com.ShizanaPlugins.${{ env.PRODUCT_NAME }}.component.pkg" 
        
#        productbuild --distribution "path to distribution.xml instructions" --resources <path to single installers(no quotes)> --package-path "Name of product.pkg"

#--------------------#--------------------#-------------------#--------------------#--------------------#--------------------
    - name: Create folder for signed installer
      if: ${{ matrix.name == 'macOS' }}
      run: mkdir ${{ env.PRODUCT_NAME }}-installer-signed

   
    - name: Notarize and staple installer
      if: ${{ matrix.name == 'macOS' }}
      run: |
        PRODUCT_NAME="${{ env.PRODUCT_NAME }}"
        USER_ID="${{ secrets.NOTARIZATION_USERNAME }}"
        NOTARIZATION_USERNAME="${{ secrets.NOTARIZATION_USERNAME }}"
        xcrun notarytool store-credentials "notarytool-password"
               --apple-id "itay.ella@gmail.com"            
               --password ${{ secrets.NOTARIZATION_PASSWORD }}
               --team-id "${{ secrets.Team_ID }}" 
        productsign --sign "${{ secrets.DEVELOPER_ID_INSTALLER }}" "${PRODUCT_NAME}_NotSign.pkg" "${PRODUCT_NAME}.pkg"
        xcrun notarytool submit "${PRODUCT_NAME}_NotSign.pkg" --keychain-profile "notarytool-password" --wait
        xcrun stapler staple "${PRODUCT_NAME}.pkg"
        
#xcrun notarytool submit "${PRODUCT_NAME}.pkg" -u "${NOTARIZATION_USERNAME}" --p "${NOTARIZATION_PASSWORD}" --team-id "${TEAM_ID}" --wait 

    - name: Create DMG
      if: ${{ matrix.name == 'macOS' }}
      run: hdiutil create Install\ ${{ env.PRODUCT_NAME }}.dmg -fs HFS+ -srcfolder ${{ env.PRODUCT_NAME }}-installer-signed -format UDZO -volname Install\ ${{ env.PRODUCT_NAME }}

    - name: Upload DMG
      if: ${{ matrix.name == 'macOS' }}
      uses: actions/upload-artifact@v2.2.1
      with:
        name: ${{ env.PRODUCT_NAME }}-installer-mac
        path: Install\ ${{ env.PRODUCT_NAME }}.dmg

    - name: Cleanup installer files
      if: ${{ matrix.name == 'macOS' }}
      uses: geekyeggo/delete-artifact@v1
      with:
        name: ${{ env.PRODUCT_NAME }}-installer-files-mac

#--------------------#--------------------#-----ZIP For Linux---------------#--------------------#--------------------#--------------------

    - name: Zip
      if: ${{ matrix.name == 'Linux' }}
      working-directory: ${{ env.ARTIFACTS_PATH }}
      run: 7z a -tzip "${{ env.ARTIFACT_NAME }}.zip" .

    - name: Generate Installer and Sign with EV cert on Azure (Windows)
      if: ${{ matrix.name == 'Windows' }}
      shell: bash
      run: |
        iscc "packaging\installer.iss"
        mv "packaging/Output/${{ env.ARTIFACT_NAME }}.exe" "${{ env.ARTIFACTS_PATH }}/"
        dotnet tool install --global AzureSignTool 
        AzureSignTool sign -kvu "${{ secrets.AZURE_KEY_VAULT_URI }}" -kvi "${{ secrets.AZURE_CLIENT_ID }}" -kvt "${{ secrets.AZURE_TENANT_ID }}" -kvs "${{ secrets.AZURE_CLIENT_SECRET }}" -kvc ${{ secrets.AZURE_CERT_NAME }} -tr http://timestamp.digicert.com -v "${{ env.ARTIFACTS_PATH }}/${{ env.ARTIFACT_NAME }}.exe"

    - name: Upload Exe (Windows)
      if: ${{ matrix.name == 'Windows' }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}.exe
        path: '${{ env.ARTIFACTS_PATH }}/${{ env.ARTIFACT_NAME }}.exe'

    - name: Upload Zip (Linux)
      if: ${{ matrix.name == 'Linux' }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}.zip
        path: '${{ env.ARTIFACTS_PATH }}/${{ env.ARTIFACT_NAME }}.zip'

    - name: Upload DMG (MacOS)
      if: ${{ matrix.name == 'macOS' }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}.dmg
        path: packaging/${{ env.ARTIFACT_NAME }}.dmg

  release:
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
    - name: Get Artifacts
      uses: actions/download-artifact@v3

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        # download-artifact puts these files in their own dirs...
        # Using globs sidesteps having to pass the version around
        files: |
          */*.exe
          */*.zip
          */*.dmg
          */*.pkg
